stages:
  - build
  - deploy
image: docker:19.03.0
services:
  - docker:19.03.0-dind

## Production
build-apps-production:
  variables:
    DOCKER_DRIVER: "overlay2"
    DOCKER_TLS_CERTDIR: ""
    REGISTRY: "registry.sofort-impfen.de"
    IMAGE_SPACE: "registry.sofort-impfen.de/si/apps"
  stage: build
  before_script:
    - docker login --username gitlab+deploy-token-6 --password $LOGIN_PASSPHRASE $REGISTRY
  script:
    - rm -rf .git
    - docker build --build-arg CI_COMMIT_SHA=${CI_COMMIT_SHA} --build-arg ENVIRONMENT=prod -t "${IMAGE_SPACE}/sofort-impfen-apps:${CI_COMMIT_SHORT_SHA}" -t "${IMAGE_SPACE}/sofort-impfen-apps:latest" .
    - docker push "${IMAGE_SPACE}/sofort-impfen-apps:${CI_COMMIT_SHORT_SHA}"
    - docker push "${IMAGE_SPACE}/sofort-impfen-apps:latest"
  only:
    refs:
      - master
      - main

deploy-apps-production:
  environment: production
  image: alpine:latest
  stage: deploy
  before_script:
    - apk add curl
  script:
    - curl -X POST "https://rundeck.sofort-impfen.de/api/19/job/d96f307f-f974-4504-9bdf-65094a0bdc66/run?authtoken=${RUNDECK_TOKEN}" --header "Content-Type:text/xml"
  variables:
    GIT_STRATEGY: none
  only:
    refs:
      - master
      - main

## Staging
build-apps-staging:
  variables:
    DOCKER_DRIVER: "overlay2"
    DOCKER_TLS_CERTDIR: ""
    REGISTRY: "registry.sofort-impfen.de"
    IMAGE_SPACE: "registry.sofort-impfen.de/si/apps"
  stage: build
  before_script:
    - echo $LOGIN_PASSPHRASE | docker login --username gitlab+deploy-token-6 --password-stdin $REGISTRY
  script:
    - rm -rf .git
    - docker build --build-arg CI_COMMIT_SHA=${CI_COMMIT_SHA} --build-arg ENVIRONMENT=staging -t "${IMAGE_SPACE}/sofort-impfen-apps:${CI_COMMIT_SHORT_SHA}" -t "${IMAGE_SPACE}/sofort-impfen-apps:staging" .
    - docker push "${IMAGE_SPACE}/sofort-impfen-apps:${CI_COMMIT_SHORT_SHA}"
    - docker push "${IMAGE_SPACE}/sofort-impfen-apps:staging"
  only:
    refs:
      - staging

deploy-apps-staging:
  environment: staging
  image: alpine:latest
  stage: deploy
  before_script:
    - apk add curl
  script:
    - curl -X POST "https://rundeck.sofort-impfen.de/api/19/job/f88ca224-ed98-4908-8ebd-ac2bd141b2d1/run?authtoken=${RUNDECK_TOKEN}" --header "Content-Type:text/xml"
  variables:
    GIT_STRATEGY: none
  only:
    refs:
      - staging
